spring.application.name=journalApp

#DB configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secretKey=65465465sdav;kaemvfknz;ofivanse[odfcs8d75f9ew8vsf64d5v68esrv68
gemini.api.key=${GEMENI_API_KEY}
gemini.api.URL=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent